print("Welcome to")
name = input("What is your name? ")
hometown = input("What is your home town?\n")
pet = input("What is your pet's name? ")
print(f"Hello, {name}, Your band name could be: {hometown} {pet}")